spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/skrshop-earth-system?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=TRUE
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
mybatis:
  mapper-locations:  classpath*:mapper/*.xml
  #  type-handlers-package: com.yh.lettue.config.mybatis
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.yh.lettue.config.mybatis.AutoEnumTypeHandler